Readme update
Azure-Samples/api-management-workspaces-migration-deprecated pull request #40
Opened 2023-04-27 23:39 UTC by dlepow

## Purpose

* Update to root Readme.md. Check whether install available from Releses.

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ x] Documentation content changes
- [ ] Other... Please describe:

## Does this introduce a breaking change?

- [ ] Yes
- [x ] No

2023-04-28 15:35 UTC, mikebudzynski requested changes

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +The tool aborts migration if it detects:
"if it detects the following scenarios unsupported in workspaces preview"

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +    The tool analyzes dependencies of selected APIs, like named values or subscriptions. See [Supported dependencies](#supported-dependencies) for the list of resources supported in the tool and [Roa
How about:

* Make this part (starting line 61) a new point and talk about the migration plan here
* Change the next point to "Confirm to execute the migration."

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +    TBD
I imagine this would also include dotnet commands to install software dependencies and compile it

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +- [.NET 6.0](https://dotnet.microsoft.com/download/dotnet/6.0)
@maciejtreder, is this .NET or .NET Core? Is Windows a prerequisite?

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +1. The tool copies the selected APIs, API version sets, and revisions into the selected workspace. It appends a random hash to the API name and API suffix to avoid conflicts.
The hash is the same for the whole migration, so we can change this text to something like "It computes a random hash and appends it to the API name and API suffix (...)"

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +    * If the dependency is used also by other APIs and doesn't allow referencing a service-level resource from a workspace-level resource, this dependency will be copied to a workspace with a random
* *the*, not *a*, hash appended to its name
* "The future iterations of the tool will still leave it undeleted."

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +    * If the dependency is used *only* by APIs that are being migrated to the workspace, the tool copies it to the workspace. In the future, the original resource on the service level will be deleted
I believe we also append hash to the name in this case, but we will change this behavior in the future.

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +    For each detected API dependency:
We have to mention that we are changing the references to the migrated dependencies. For example, if a product is migrated, we will change the product assignment in a migrated API to point to the migrated product instead.

2023-04-28 15:35 UTC, mikebudzynski commented on README.md
> +
1. Download / check out the tool from the releases section. The `main` branch may contain unstable or untested code.

2023-05-02 08:48 UTC, tomkerkhove commented on README.md
>  ## Telemetry
Let's push this right before license maybe? Majority of folks does not care about it

2023-05-09 23:03 UTC, dlepow commented on README.md
> +The tool aborts migration if it detects:
Updated as suggested

2023-05-09 23:03 UTC, dlepow commented on README.md
> +    The tool analyzes dependencies of selected APIs, like named values or subscriptions. See [Supported dependencies](#supported-dependencies) for the list of resources supported in the tool and [Roa
Updated as suggested.

2023-05-09 23:04 UTC, dlepow commented on README.md
> +    TBD
Added dotnet build/run commands

2023-05-09 23:04 UTC, dlepow commented on README.md
> +- [.NET 6.0](https://dotnet.microsoft.com/download/dotnet/6.0)
Currently the name is just ".NET". AFAIK Windows is not required.

2023-05-09 23:04 UTC, dlepow commented on README.md
> +1. The tool copies the selected APIs, API version sets, and revisions into the selected workspace. It appends a random hash to the API name and API suffix to avoid conflicts.
Changed as suggested

2023-05-09 23:05 UTC, dlepow commented on README.md
> +    * If the dependency is used also by other APIs and doesn't allow referencing a service-level resource from a workspace-level resource, this dependency will be copied to a workspace with a random
Changed as suggested

2023-05-09 23:09 UTC, dlepow commented on README.md
> +    * If the dependency is used *only* by APIs that are being migrated to the workspace, the tool copies it to the workspace. In the future, the original resource on the service level will be deleted
Updated as suggested.

2023-05-09 23:09 UTC, dlepow commented on README.md
> +
I didn't mention a releases section - don't see it used currently. I provided `git clone` steps for now (from main).

2023-05-09 23:10 UTC, dlepow commented on README.md
>  ## Telemetry
Moved as suggested - thanks.

2023-05-09 23:10 UTC, dlepow commented on README.md
> +    For each detected API dependency:
Added Note: 
"Note: Migrated APIs in a workspace are updated to reference any dependency that's migrated to the workspace. For example, if a dependent product is migrated, the product assignment in a migrated API is updated to point to the migrated product instead."

2023-05-11 21:27 UTC, mikebudzynski approved these changes

2023-05-11 21:29 UTC, merged